# Generated by Django 4.2.3 on 2023-08-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='taskModel',
            fields=[
                ('taskNo', models.IntegerField(primary_key=True, serialize=False)),
                ('taskTitle', models.CharField(max_length=40)),
                ('taskDescription', models.CharField(max_length=100)),
                ('is_completed', models.BooleanField()),
            ],
        ),
    ]
